package com.micropractice.app;

import android.app.Activity;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import java.util.Locale;

public class MainActivity extends Activity {
    LinearLayout root, content, nav; SharedPreferences prefs; int blue=Color.rgb(49,92,255), text=Color.rgb(31,35,48), muted=Color.rgb(112,118,134), bg=Color.rgb(247,248,252);
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
    TextView tv(String s,float size,int color){ TextView v=new TextView(this); v.setText(s); v.setTextSize(size); v.setTextColor(color); v.setGravity(Gravity.CENTER_VERTICAL); return v; }
    Button btn(String s){ Button b=new Button(this); b.setText(s); b.setTextSize(15); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setBackgroundColor(blue); b.setPadding(dp(18),0,dp(18),0); return b; }
    TextView title(String s){ TextView v=tv(s,28,text); v.setTypeface(Typeface.DEFAULT,Typeface.BOLD); v.setPadding(dp(20),dp(22),dp(20),dp(8)); return v; }
    TextView cardText(String s){ TextView v=tv(s,16,text); v.setPadding(dp(18),dp(16),dp(18),dp(16)); v.setBackgroundColor(Color.WHITE); return v; }
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("micro",0); showHome();}
    void base(){ root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(bg); setContentView(root); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); root.addView(content,new LinearLayout.LayoutParams(-1,0,1)); nav=new LinearLayout(this); nav.setGravity(Gravity.CENTER); nav.setBackgroundColor(Color.WHITE); root.addView(nav,new LinearLayout.LayoutParams(-1,dp(68))); String[] ns={"首页","练习","成长","我的"}; for(String n:ns){TextView x=tv(n,13,muted); x.setGravity(Gravity.CENTER); nav.addView(x,new LinearLayout.LayoutParams(0,-1,1)); if(n.equals("首页"))x.setTextColor(blue); x.setOnClickListener(v->{ if(n.equals("首页"))showHome(); else if(n.equals("练习"))showPractice(); else if(n.equals("成长"))showGrowth(); else showMe(); });}}
    void showHome(){base(); content.addView(title("微练")); TextView sub=tv("先让你开始，再帮你变强。",15,muted); sub.setPadding(dp(20),0,dp(20),dp(18)); content.addView(sub); TextView streak=cardText("今日状态\n\n最小承诺：写一句英文\n预计只需 1 分钟\n\n完成最小动作，就是今天的成功。",16,text); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(180)); cp.setMargins(dp(16),0,dp(16),dp(14)); content.addView(streak,cp); Button go=btn("开始今天的微练"); LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(54)); bp.setMargins(dp(20),dp(6),dp(20),0); content.addView(go,bp); go.setOnClickListener(v->minimumAction()); TextView tip=tv("不追求连续打卡，只追求真正进步。",14,muted); tip.setGravity(Gravity.CENTER); content.addView(tip,new LinearLayout.LayoutParams(-1,dp(60))); }
    void minimumAction(){base(); content.addView(title("最小行动")); TextView task=cardText("今天只做一件事\n\n用英语写一句话：\n“I want to get better at ______ because ______.”\n\n写完即可结束，绝不要求你继续。",17,text); LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(240));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(task,p); EditText input=new EditText(this); input.setHint("写下你的句子…"); input.setTextSize(17); input.setSingleLine(false); input.setBackgroundColor(Color.WHITE); LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(100));ip.setMargins(dp(16),0,dp(16),dp(14));content.addView(input,ip); Button done=btn("完成最小行动"); LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(54));bp.setMargins(dp(20),0,dp(20),0);content.addView(done,bp);done.setOnClickListener(v->{ if(input.getText().toString().trim().length()==0){Toast.makeText(this,"先写一句就好。",Toast.LENGTH_SHORT).show();return;} prefs.edit().putInt("done",prefs.getInt("done",0)+1).apply(); afterMinimum();}); }
    void afterMinimum(){base(); content.addView(title("今天已经成功")); TextView ok=cardText("最小承诺完成 ✓\n\n你现在可以停下来。完成最小行动本身就是成功。",17,text); LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(150));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(ok,p); Button stop=btn("今天就到这里"); Button more=btn("我想继续练"); LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(54));q.setMargins(dp(20),0,dp(20),dp(10));content.addView(stop,q); LinearLayout.LayoutParams r=new LinearLayout.LayoutParams(-1,dp(54));r.setMargins(dp(20),0,dp(20),0);content.addView(more,r);stop.setOnClickListener(v->showHome());more.setOnClickListener(v->deliberate()); }
    void showPractice(){base();content.addView(title("刻意练习")); TextView c=cardText("今天的训练目标\n\n弱点：表达不够具体\n训练方式：把一句普通表达改得更清晰\n\n专注 5 分钟，只练一个弱点。",16,text);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(190));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(c,p);Button b=btn("开始 5 分钟训练");LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(54));q.setMargins(dp(20),0,dp(20),0);content.addView(b,q);b.setOnClickListener(v->deliberate());}
    void deliberate(){base();content.addView(title("专注训练"));TextView timer=tv("05:00",42,blue);timer.setGravity(Gravity.CENTER);content.addView(timer,new LinearLayout.LayoutParams(-1,dp(90)));TextView prompt=cardText("把这句话改得更具体：\n“我最近很忙。”\n\n要求：增加一个时间、一个行动、一个结果。",17,text);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(170));p.setMargins(dp(16),0,dp(16),dp(12));content.addView(prompt,p);EditText answer=new EditText(this);answer.setHint("你的改写…");answer.setTextSize(17);answer.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(100));ap.setMargins(dp(16),0,dp(16),dp(12));content.addView(answer,ap);Button finish=btn("提交并获得反馈");LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(54));fp.setMargins(dp(20),0,dp(20),0);content.addView(finish,fp);finish.setOnClickListener(v->{ if(answer.getText().toString().trim().length()<6){Toast.makeText(this,"再具体一点，再试一次。",Toast.LENGTH_SHORT).show();return;} prefs.edit().putInt("practice",prefs.getInt("practice",0)+1).apply();feedback();}); }
    void feedback(){base();content.addView(title("即时反馈"));TextView f=cardText("做得不错。\n\n本次只看一个重点：具体性。\n如果你的句子包含了“什么时候 + 做了什么 + 得到什么结果”，就达成了训练目标。\n\n下一次：保留结构，再把结果写得更可验证。",16,text);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(250));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(f,p);Button b=btn("再练一次");LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(54));q.setMargins(dp(20),0,dp(20),0);content.addView(b,q);b.setOnClickListener(v->deliberate());}
    void showGrowth(){base();content.addView(title("成长"));int d=prefs.getInt("done",0),pr=prefs.getInt("practice",0);TextView g=cardText(String.format(Locale.CHINA,"你的成长不是打卡次数，而是能力证据。\n\n最小行动完成：%d 次\n刻意练习完成：%d 次\n\n当前技能：英语表达\n等级：Lv.1 起步者\n\n下一突破：连续完成 3 次针对同一弱点的有效练习。",d,pr),16,text);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(270));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(g,p);}
    void showMe(){base();content.addView(title("我的"));TextView m=cardText("微练 MicroPractice\n\n训练原则\n• 最小行动，小到无法拒绝\n• 可以完成最小动作后随时停止\n• 刻意练习一次只攻一个弱点\n• 用能力证据，而不是连续天数衡量成长\n\n版本 1.0 MVP",16,text);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(330));p.setMargins(dp(16),0,dp(16),dp(18));content.addView(m,p);}
}
